# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.wesleyq.me/
title: Wesley W. Q.
email: wesley.chin0919@gmail.com
author: Wesley Wei Qian
description: > # "Wesley Wei Qian's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/wesleychin0919
  - icon: flask
    title: scholar
    url: https://scholar.google.com/citations?user=SZ5EErcAAAAJ&hl=en
  - icon: github
    title: github
    url: https://github.com/WesleyyC
  - icon: twitter
    title: twitter
    url: https://twitter.com/WesleyQian
  - icon: file-pdf-o
    title: resume
    url: http://www.wesleyq.me/rsc/resume.pdf
  - icon: envelope-o
    title: email
    url: mailto:wesley.chin0919@gmail.com