#!/bin/sh
set -eu

SITE_TEST_DIR=$(mktemp -d "${TMPDIR:-/tmp}/personal-page-test.XXXXXX")

cleanup() {
    rm -rf -- "$SITE_TEST_DIR"
}
trap cleanup EXIT

if [ -x /opt/homebrew/opt/ruby/bin/bundle ]; then
    BUNDLE_BIN=/opt/homebrew/opt/ruby/bin/bundle
    RUBY_BIN=/opt/homebrew/opt/ruby/bin/ruby
else
    BUNDLE_BIN=$(command -v bundle)
    RUBY_BIN=$(command -v ruby)
fi

"$BUNDLE_BIN" exec jekyll build --destination "$SITE_TEST_DIR"
SITE_DIR="$SITE_TEST_DIR" "$BUNDLE_BIN" exec "$RUBY_BIN" test/site_contract_test.rb
