#!/bin/sh
set -eu

if [ -x /opt/homebrew/opt/ruby/bin/ruby ]; then
    RUBY_BIN=/opt/homebrew/opt/ruby/bin/ruby
else
    RUBY_BIN=$(command -v ruby)
fi

"$RUBY_BIN" test/static_public_contract_test.rb
node test/menu_scroll_behavior_test.js
